config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
get 'beers', to: 'beers#index'
get 'beers/:id', to:'beers#show', as: 'show_beer'
get 'beers/new', as: 'new_beer'
post 'beers', to: 'beers#create'
get 'beers/:id/edit', to:'beers#edit', as: 'edit_beer'
patch 'beers/:id', to: 'beers#update', as: 'beer'
delete 'beers/:id', to: 'beers#destroy', as: 'delete_beer'


root 'beers#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/beer.rb
class Beer < ApplicationRecord
    validates :name, presence: {message: 'No puedo ser creada sin nombre'}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/beers_controller.rb
class BeersController < ApplicationController
before_action :set_beer, only: [:edit, :show, :update, :destroy]
   
    def index
        @beers = Beer.all 
    end
    def new
       @beer = Beer.new 
    end

    def edit  
    end
    
    def show
    end

    def update
    @beer.uptade(beer_params)
    redirect_to beers_path
    end

    def create
        @beer = Beer.new(beer_params)
       if @beer.save
        redirect_to beers_path
       else 
        render :new
       end
    end

    def destroy
    @beer.destroy
    redirect_to beers_path
    end
    

 private

 def set_beer
    @beer = Beer.find(params[:id])
 end
 

 def beer_params
    params.require(:beer).permit(:name, :price, :description, :available, :picture)
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/beers/_form.html.erb
<% if beer.errors.any?%>
  <ul>
  <% beer.errors.full_messages.each do |error|%>
<li><%= error %></li>
<% end %>
  </ul>
<% end %>
<div class='row'>
<div class="col-md-6 offset-md-3">
<%= form_with(model: beer, local:true) do |f|%>
<div class= "form-group">
<%= f.label :name %>
<%= f.text_field :name, class: 'form-control'%>
</div>
<br>
<div class= "form-check">
<%= f.check_box :available, class: 'form-check-input' %>
<%= f.label :available, class: 'form-check-label', for:'available'%>
</div>
<br>
<div class= "form-group">
<%= f.label :price %>
<%= f.number_field :price, class: 'form-control' %>
</div>
<br>
<div class= "form-group">
<%= f.label :picture %>
<%= f.text_field :picture, class: 'form-control' %>
</div>
<br>
<div class= "form-group">
<%= f.label :description %>
<%= f.text_area :description, class: 'form-control' %>
</div>
<br>
<%= f.submit class: 'btn btn-info btn-block'%>
<% end %>
 </div>
</div>

app/views/beers/edit.html.erb
<h1 class= 'text-center'> Edit Chela</h1>

<%= render 'form', beer: @beer %>

app/views/beers/index.html.erb
<div class="card-deck">
<% @beers.each do |beer|%>
  <div class="card">
    <%= image_tag beer.picture, class:'card-img-top', 'heigth': '500px', 'width': '200px' %>
    <div class="card-body">
      <h5 class="card-title"><%= beer.name %></h5>
      <p class="card-text"><%= beer.description%></p>
      <p class="card-text"><%= beer.price %></p>
       <p class="card-text"><%= beer.available ? 'Disponible' : 'Agotada' %></p>
      <p class="card-text"><small class="text-muted">Last update: <% time_ago_in_words(beer.created_at)%></small></p>
    <%= link_to "Edit", edit_beer_path(beer)%>
     <%= link_to "Delete", delete_beer_path(beer), method: :delete, data: {confirm: 'Are you sure?'} %>
     <%= link_to "Ver", show_beer_path(beer)%>
    </div>
  </div>
  <% end %>
  </div>

  <%= link_to "Nueva Chela", new_beer_path %>

app/views/beers/new.html.erb
<h1 class= 'text-center'> New Chela</h1>

<%= render 'form', beer: @beer %>

app/views/beers/show.html.erb
<div class="card-deck">

  <div class="card">
    <%= image_tag @beer.picture, class:'card-img-top', 'heigth': '500px', 'width': '200px' %>
    <div class="card-body">
      <h5 class="card-title"><%= @beer.name %></h5>
      <p class="card-text"><%= @beer.description%></p>
      <p class="card-text"><%= @beer.price %></p>
       <p class="card-text"><%= @beer.available ? 'Disponible' : 'Agotada' %></p>
      <p class="card-text"><small class="text-muted">Last update: <% time_ago_in_words(@beer.created_at)%></small></p>
    <%= link_to "Edit", edit_beer_path(@beer)%>
     <%= link_to "Delete", delete_beer_path(@beer), method: :delete, data: {confirm: 'Are you sure?'} %>

    </div>
  </div>
 
  </div>

  <%= link_to "<<Back", root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ManualCrud</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <%= yield %>
  </body>
</html>